spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
#    password: password
    driverClassName: org.h2.Driver

server:
  port: 5000
