version: 0.2

#run-as: aws-ubuntu


#proxy:
#  upload-artifacts: no
#  logs: yes

phases:
  install:
#    run-as: aws-ubuntu
#    on-failure: ABORT | CONTINUE
    commands:
      - apt update -y
      - apt install default-jre -y
#    finally:
#      - command
#      - command
#  pre_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
  build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - echo "Hello World!!"
      - java --version
      - pwd
      - ls
    finally:
      - echo "Completed Running all the commands"

#  post_build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
#    commands:
#      - command
#      - command
#    finally:
#      - command
#      - command
