version: 0.2

#run-as: aws-ubuntu


#proxy:
#  upload-artifacts: no
#  logs: yes

phases:
  install:
#    run-as: aws-ubuntu
#    on-failure: ABORT | CONTINUE
    commands:
      - apt update -y
      - apt install default-jre -y
#    finally:
#      - command
#      - command
  pre_build:
    commands:
      - echo "Pre-Build Stage"
      - ls
      - mvn clean
    finally:
      - echo "Completed Pre-Build Stage"
  build:
#    run-as: Linux-user-name
#    on-failure: ABORT | CONTINUE
    commands:
      - ls
      - mvn install package

    finally:
      - echo "Completed Running all the commands"

  post_build:
#    commands:
#      - command
#      - command
    finally:
      - echo "Finally completed the build!"

